### ISSUE TITLE
⚠️ actions-runner-controller repository transfer notice

### ISSUE THREAD

**Issue by Link-** [actions/actions-runner-controller#2089]
Following [this announcement](https://github.com/actions-runner-controller/actions-runner-controller/discussions/2072) this repository will be transferred to https://github/actions at `11:00AM CET today (Monday December 12th 2022)`.

We will publish migration updates in this issue.

**Comment by Link-** [comment]
ARC repository transfer has started now: `11:00AM CET`

**Comment by Link-** [comment]
### Update 11:26AM

The released packages were moved over to this mirror and as such `helm upgrade` fails with the following error:
```
Release "actions-runner-controller" does not exist. Installing it now.
Error: failed to fetch https://github.com/actions-runner-controller/actions-runner-controller/releases/download/actions-runner-controller-0.21.1/actions-runner-controller-0.21.1.tgz : 404 Not Found
```

We're currently considering the fastest remediation and we'll update this issue with further information.

**Comment by fhammerl** [comment]
## Update 11:33AM

The helm installation failed because it required released binaries at `actions-runner-controller/actions-runner-controller`.

These binaries were *moved* to `actions/actions-runner-controller` to this location:
https://github.com/actions-runner-controller/actions-runner-controller/releases/download/actions-runner-controller-0.21.1/actions-runner-controller-0.21.1.tgz

As temporary remediation, we have manually re-uploaded this archive to the last few releases under `actions-runner-controller/actions-runner-controller`.

The helm charts (still expecting the archive to be under `actions-runner-controller/actions-runner-controller`) now work.

**Comment by Link-** [comment]
### Update 11:55 AM

@mumoshu has created https://github.com/actions-runner-controller/actions-runner-controller/pull/4 to point to the new location of the released binaries however this will require end users to re-add their helm repositories. This is something we've been trying to avoid initiatially.

We're currently considering pull and re-uploading all the old release binaries from the transferred repo to this mirror.

**Comment by Link-** [comment]
### Update 12:52 PM

All releases (up to `v0.3.1`) have been ported from https://github.com/actions/actions-runner-controller/releases to https://github.com/actions-runner-controller/actions-runner-controller/releases

**Comment by Link-** [comment]
### Update 01:00 PM

Transfer has been **completed** successfully.

Major thanks to @nikola-jokic @rentziass @fhammerl for being part of this effort ✨ 

Please don't hesitate to report any issues via: [this link](https://github.com/actions/actions-runner-controller/issues/new/choose)

### Action items
- [ ] Review access permissions for contributors and collaborators
- [ ] Revisit the helm chart release and GitHub pages publication mechanism
- [ ] Revisit the GitHub Packages linkage
- [ ] Revisit CODEOWNERS

**Comment by Link-** [comment]
Closing this issue as completed.
