### ISSUE TITLE
Still present random `SIGSEGV segmentation violation` in `action-metrics-server` 

### ISSUE THREAD

**Issue by ozlotusflare** [actions/actions-runner-controller#2424]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.1

### Helm Chart Version

0.22.0

### CertManager Version

v1.11.0

### Deployment Method

Helm

### cert-manager installation

Installet correctly

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
image:
  tag: v0.27.1
  pullPolicy: Always
actionsMetricsServer:
  enabled: true
```

### To Reproduce

```markdown
Run `actionsMetricsServer` with a latest image
```

### Describe the bug

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1420079]

goroutine 15 [running]:
github.com/actions/actions-runner-controller/pkg/actionsmetrics.(*EventReader).fetchAndParseWorkflowJobLogs(0x1583e40?, {0x19d0ed0?, 0xc0001a2000?}, 0xe?)
	github.com/actions/actions-runner-controller/pkg/actionsmetrics/event_reader.go:208 +0x59
github.com/actions/actions-runner-controller/pkg/actionsmetrics.(*EventReader).ProcessWorkflowJobEvent(0xc00018abd0, {0x19d0ed0, 0xc0001a2000}, {0x15fa880?, 0xc0005f01b0})
	github.com/actions/actions-runner-controller/pkg/actionsmetrics/event_reader.go:139 +0x105b
github.com/actions/actions-runner-controller/pkg/actionsmetrics.(*EventReader).ProcessWorkflowJobEvents(0xc00018abd0, {0x19d0ed0, 0xc0001a2000})
	github.com/actions/actions-runner-controller/pkg/actionsmetrics/event_reader.go:44 +0x59
main.main.func1()
	github.com/actions/actions-runner-controller/cmd/actionsmetricsserver/main.go:157 +0x6c
created by main.main
	github.com/actions/actions-runner-controller/cmd/actionsmetricsserver/main.go:154 +0xdef
```

### Describe the expected behavior

See the metrics

### Whole Controller Logs

```shell
Controller logs is fine
```

### Whole Runner Pod Logs

```shell
Runner logs is fine
```

### Additional Context

Related issue: https://github.com/actions/actions-runner-controller/issues/2309

**Comment by zanehala-wk** [comment]
+1, hitting this same issue.

**Comment by WissemChb** [comment]
+1, having the same issue.

**Comment by dongho-jung** [comment]
I had the same issue. So I did some digging and found out that [this line](https://github.com/actions/actions-runner-controller/blob/c23e31123c365f4f2bdee4d8b84b9dd48e246d56/pkg/actionsmetrics/event_reader.go#L208)'s reader.GitHubClient was nil. The reader.GitHubClient is set in the [this line](https://github.com/actions/actions-runner-controller/blob/c23e31123c365f4f2bdee4d8b84b9dd48e246d56/cmd/actionsmetricsserver/main.go#L136). However, in order for this property to be set, the conditions in [this line](https://github.com/actions/actions-runner-controller/blob/c23e31123c365f4f2bdee4d8b84b9dd48e246d56/cmd/actionsmetricsserver/main.go#L123) must be met.

Come to think of it, it was strange. I was sure I had set the github_webhook_secret_token, but upon checking, there was no secret called actions-metrics-server. actionsMetricsServer.enabled and actionsMetricsServer.secret.create were definitely true.

After some time, it turned out that the necessary file for creating this secret was missing in the ChartVersion=0.22.0 release.
I checked the last chart app version and you can also download and check [actions-runner-controller-0.22.0.tgz](https://github.com/actions/actions-runner-controller/releases/tag/actions-runner-controller-0.22.0)

@mumoshu maybe chart version should be updated too?

**Comment by mumoshu** [comment]
Thank you everyone for reporting and @0xF4D3C0D3 for the detailed feedback!
FYI, I've released the new chart version today.
I'll shortly fix the issue and publish the next patch version for the controller.
