### ISSUE TITLE
Provide base manifests for scale sets as an alternative to Helm chart

### ISSUE THREAD

**Issue by cartucciam** [actions/actions-runner-controller#2673]
It would be nice having base manifests we can use in kustomize as an alternative to Helm.

Current limitations of having only Helm:
- Helm does not manage CRDs other than installing them
- Not possible to use OCI Helm charts in Kustomize https://github.com/kubernetes-sigs/kustomize/pull/5167
- Doesn't support adding simple patches (e.g. adding requests and limits to the controller deployment)

**Comment by Link-** [comment]
We're not going to provide Kustomize files for autoscaling runner sets or legacy modes of ARC. You can (relatively) easily generate templates via `helm --template` and use the output whichever way you like.

I'm closing this issue because the decision has been made to use helm for all future releases.

**Comment by cartucciam** [comment]
Thanks for the reply, can you share the rationale for this decision? You are right, this can be done but I disagree on the relatively easily bit, in fact this decision makes it quite cumbersome managing it via ArgoCD at least until Kustomize adds support for OCI Helm repos. In my experience Helm is nice but simply doesn't fit the bill for platform operators. This decision forces people to do unnecessary hacks for trivial things like adding requests, limits and other minor patches.
