### ISSUE TITLE
Cache docker image layers

### ISSUE THREAD

**Issue by johannesnormannjensen** [actions/actions-runner-controller#2744]
### What would you like added?

Could it be possible to cache docker image layers using the Runner Scale Set architecture?

Note: Feature requests to integrate vendor specific cloud tools (e.g. `awscli`, `gcloud-sdk`, `azure-cli`) will likely be rejected as the Runner image aims to be vendor agnostic.

### Why is this needed?

This is needed for people using Runner Scale Set with large sidecar/services in their github workflows. I don't have any idea how to implement this as I'm a k8s newbie. 

### Additional context

I'm using mcr.microsoft.com/mssql/server:2019-latest as a service in one of my workflows and the time it takes to pull that image is very long. This would improve performance greatly in my case (maybe other too).

**Comment by nikola-jokic** [comment]
Hey @johannesnormannjensen,

To provide more context, the scale set is not really responsible for image management. Essentially, controllers alongside with the listener are responsible for communicating with the actions service. Once there is a need to scale up or down, controllers are creating resources (or deleting) by issuing API requests to the kubernetes. The image definition of the runner specified when configuring `AutoscalingRunnerSet` will be used to express an intent to create a runner pod.

Once the request has been made, the kubelet is responsible for fetching the image and spinning it up. The controller is not responsible for assigning the image to a specific node either :relaxed:. It falls under the responsibility of the scheduler itself, which can be influenced by the pod spec configured in the `AutoscalingRunnerSet`. Now, since we don't control the node, we can't pre-cache image layers on it.

However, you can maybe leverage something like `kube-fledged` :relaxed:

**Comment by nikola-jokic** [comment]
I will close this issue, since this is not the responsibility of the controllers. But feel free to comment on it :relaxed:

**Comment by regenscheid** [comment]
@nikola-jokic -

> However, you can maybe leverage something like `kube-fledged` ☺️

I just tried setting up kube-fledged, and stumbled onto this issue when I started searching for ways to troubleshoot it when I couldn't get ARC runners to pull from the kube-fledged cache.  I'm still pretty naive when it comes to Kubernetes, so I honestly don't even know if this is an expected limitation.

Right now I have a Talos-based cluster running ARC.  The Github Actions job runs docker-compose on a large image, so I want to cache it. But right now its clearly pulling the image every time, and there's no sign from the Kube-fledged logs that it even tries to get it from there.

Is there any special configuration that's necessary on the ARC side to get it to use the kube-fledged image cache?

**Comment by johannesnormannjensen** [comment]
> Hey @johannesnormannjensen,
> 
> To provide more context, the scale set is not really responsible for image management. Essentially, controllers alongside with the listener are responsible for communicating with the actions service. Once there is a need to scale up or down, controllers are creating resources (or deleting) by issuing API requests to the kubernetes. The image definition of the runner specified when configuring `AutoscalingRunnerSet` will be used to express an intent to create a runner pod.
> 
> Once the request has been made, the kubelet is responsible for fetching the image and spinning it up. The controller is not responsible for assigning the image to a specific node either ☺️. It falls under the responsibility of the scheduler itself, which can be influenced by the pod spec configured in the `AutoscalingRunnerSet`. Now, since we don't control the node, we can't pre-cache image layers on it.
> 
> However, you can maybe leverage something like `kube-fledged` ☺️

Thank you so much! This gave me some ideas on how i could continue. Sorry for not replying!
