### ISSUE TITLE
Allow specifying Runner's ServiceAccount annotations

### ISSUE THREAD

**Issue by rgarrigue** [actions/actions-runner-controller#2834]
### What would you like added?

Defining a RunnerDeployment, it creates a RunnerReplicatSet which spawns the Runner, which create a pod + serviceAccount + role + roleBinding. While defining the RunnerDeployment I want to be able to specify the ServiceAccount annotations  

### Why is this needed?

Running on AWS, you can use IRSA (IAM Role for Service Account) to grant permission to specific pods. In my case I want to allow my runners to push  container images to ECR

**Comment by Morishiri** [comment]
You can specify `serviceAccountName` in `RunnerDeployment` and create this `ServiceAccount` with the annotations you like. I did it this way and it works.

**Comment by darrell-hart** [comment]
I want to be able to specify the ServiceAccount annotations in the gha-runner-scale-set values.yaml as well in the same way it's possible in the gha-runner-scale-set-controller [values.yaml](https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set-controller/values.yaml#L32-L40) file.   Being able to add annotations to the runner will allow use of IRSA.

**Comment by darpham** [comment]
Rather than using IRSA, I would recommend utilizing OIDC, this also gives the added benefit of being more explicit on which IAM Role to assume per GHA Workflow / Job

- https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
- https://github.com/aws-actions/configure-aws-credentials
- https://github.com/unfunco/terraform-aws-oidc-github

**Comment by rgarrigue** [comment]
> You can specify `serviceAccountName` in `RunnerDeployment` and create this `ServiceAccount` with the annotations you like. I did it this way and it works.

Did the trick for me, thanks ! 

@darpham I get your point, it's more accurately secure, but in my scale that's overkill. I already use IRSA, one more way to do things would add complexity, I can just have a couple more RunnerDeployment for the handful of security persona I have.

**Comment by darpham** [comment]
> > You can specify `serviceAccountName` in `RunnerDeployment` and create this `ServiceAccount` with the annotations you like. I did it this way and it works.
> 
> Did the trick for me, thanks !
> 
> @darpham I get your point, it's more accurately secure, but in my scale that's overkill. I already use IRSA, one more way to do things would add complexity, I can just have a couple more RunnerDeployment for the handful of security persona I have.

Glad you were able to figure it out!
I'm usually inclined to agree, especially since IRSA was made specifically with K8s ServiceAccount + IAM Roles in mind.
However Github Actions runners break the mold / intended purpose of IRSA in my mind. Where a given pod usually has 1 process / responsibility - Github Action runners fulfill many responsibilities (builds, testing, packaging, deployments, etc. across many repositories)
Additionally, most developers don't harden the [Actions permissions around their repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#controlling-changes-from-forks-to-workflows-in-public-repositories), it leaves quite the security vulnerability.

For what it's worth, I also initially tried to add ServiceAccount annotation for IRSA, so I'm with with you on this one 👍

**Comment by jklemm** [comment]
> You can specify `serviceAccountName` in `RunnerDeployment` and create this `ServiceAccount` with the annotations you like. I did it this way and it works.

How to make this work, using `gha-runner-scale-set-controller` and `gha-runner-scale-set`?

The controller have "serviceAccount" attribute, but it's only applyed to controller pod (scale up pods, ...).
The runners generated by "runner-scale-set" don't have a "serviceAccount" or "serviceAccountName" attribute.
