### ISSUE TITLE
Add Scheduled Overrides to gha-runner-scale-set

### ISSUE THREAD

**Issue by Moser-ss** [actions/actions-runner-controller#2986]
### What would you like added?

In the `HorizontalRunnerAutoscaler` we have the capability to overwrite the minimum number of runners based on schedule rules.
This feature is important when we need to scale down the runners during the night and on weekends.

In the `AutoscalingRunnerSet` we don't have this capability 

### Why is this needed?

This feature is needed to allow the possibility to scale the minimal number of runners during the off hours so we don't have unnecessary runners in standby mode 

### Additional context

We can replicate the same syntax we have in the HRA like we see [here](https://github.com/actions/actions-runner-controller/blob/master/docs/automatically-scaling-runners.md#scheduled-overrides)  but we could discuss other formats

**Comment by Link-** [comment]
@Moser-ss - that's not a feature we will be adding to the new modes. With the ability to configure a min and a max number of runners, you can setup your own scheduled job to run a chart update and set the new values.

**Comment by hawkesn** [comment]
@Link- , for those using FluxCD or ArgoCD, the values for the charts are stored in Git. 

Creating a scheduled job to write Git values back into the repo isn't good practice. We've previously used the scheduledOverrides feature from ARC with great success.
scheduledOverrides allows us to maintain a minimum set of Runners during developers work hours and bring it down to zero when they are not working.

The time it takes for new runners to 
1. Dynamically provision new ec2 instances via cluster-autoscaler/Karpenter (since we want to keep this at zero to reduce costs)
2. Get scheduled on the ec2 instance
3. Register with GitHub as a Runner
takes approximately 3-5 minutes. 

This can be frustrating for jobs that take no more than 30 seconds. Even if we skip step 1 and an ec2 is already present, it still takes a minute or two to register a Runner.

If possible, I hope the team can reconsider their stance on the scheduledOverrides.
Thank you!

**Comment by adziura-ledger** [comment]
+1

**Comment by asafhm** [comment]
@Link- Why has this been closed so quickly? This is obviously a very sought-after feature that clearly worked perfectly before and can save a fortune for those who run it on public clouds.
On a more personal note, this is probably the main reason I consider reverting to the old runner controller...

**Comment by asafhm** [comment]
I've created PR #3564 to address this need
