### ISSUE TITLE
Networking with services is not available with containerMode=kubernetes

### ISSUE THREAD

**Issue by youroff** [actions/actions-runner-controller#3073]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.6.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Try to run any job with services (test with database container) and get the domain not found error message.
```

### Describe the bug

It's not a bug, but rather misleading part of documentation. Quoting:

> In Kubernetes mode, ARC uses runner container hooks to create a new pod in the same namespace to run the **service**, container job, or action.

It reads like everything should be fine, and it does indeed start the service, but it's unreachable from the steps of the job. I just spent a day hitting my head against the wall trying to make it work, only to discover the following note in the container hooks repository, and I'm still not sure I understand why would anyone want a service that they can't use from the main parts of workflow. https://github.com/actions/runner-container-hooks/blob/main/packages/k8s/README.md?plain=1#L44

### Describe the expected behavior

ideally it should allow for networking between pods in one job (https://kubernetes.io/docs/tasks/job/job-with-pod-to-pod-communication/), but as a noob in kubernetes I might be missing something.

### Additional Context

```yaml
...
```

### Controller Logs

```shell
...
```

### Runner Pod Logs

```shell
...
```

**Comment by nikola-jokic** [comment]
Hey @youroff,

As you mentioned, it is documented in the hook that step containers can't access services. However, job container services are accessible using `localhost`.
Job pod consists of job container and service containers, and they all share the same network. On the other hand, container action (i.e. docker action) is created as a separate pod (more specifically, a job that creates a pod), so it does not have access to the others pod network. To get around that, we would have to expose node ports (and extend permissions to create services), or have a side-car containers to create a link between them (but there is another problem, which container should be used?). 

Since hook was meant to be a good starting point and an implementation that fits most cases, we proceeded with this limitation.

Since this is a hook issue, I will close it here.

**Comment by youroff** [comment]
@nikola-jokic Thank you for a hint, we used service name when the job was in container, so now it's the other way around and we can probably live with that. Would it make sense to add this bit to the main guide for ARC? I feel like an average person setting up ARC would never end up in a container-hooks repo to dig that information, and it would be nice to know the options right away. I can provide a PR if it makes sense.
