### ISSUE TITLE
workflow with "Pending" status mark job as failed

### ISSUE THREAD

**Issue by turbotankist** [actions/actions-runner-controller#3232]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.1

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
We use a karpenter to run nodes in out eks cluster.
So we have no permanent running nodes.
1. We have gha-runner-listener pod. 
2. The job was triggered
3. The pod gha-runner-qlpzg-runner-lmrrp was started
4. Then start creating the pod gha-runner-qlpzg-runner-lmrrp-workflow. But it has cpu/memory requests. 
5. We need to wait until the karpenter start new nodes. But gha-runner-qlpzg-runner-lmrrp-workflow was finished with status OutOfmemory or OutOfcpu
```

### Describe the bug

gha-runner-qlpzg-runner-lmrrp-workflow was finished with status OutOfmemory or OutOfcpu 
but mast wait until the karpenter start new nodes.

### Describe the expected behavior

gha-runner-qlpzg-runner-lmrrp-workflow stays in Pending state for 2 minutes and run succesfuly.

### Additional Context

```yaml
we use external kubernetesModeWorkVolumeClaim - aws gp3, so we don't need run it on the same node? 
```

### Controller Logs

```shell
-
```

### Runner Pod Logs

```shell
-
```

**Comment by nikola-jokic** [comment]
Hey @turbotankist,

To make sure I understood, the order of "events" is:
1. Runner pod started on some node
2. Runner receives a job
3. Runner invokes the hook to create a workflow pod
4. Hook creates a workflow pod, which causes memory pressure, effectively killing the runner with the out-of-memory issue.

If that is the case, there is nothing we can do here to fix this problem. Once the job lands on the runner, the runner owns it and starts its execution. I assume that you are running the hook without any modification, and the default implementation of the hook is not to lean on the scheduler but to assign the same node where the runner is.

The issue can be avoided by leveraging ReadWriteMany volumes if your cluster allows it. The newest hook implementation allows the job pod to land on a different node if the volume shared between the runner and the hook is ReadWriteMany. Otherwise, the job pod needs to land on the same node to share files with the runner. You can probably specify requests for the runner slightly higher to have a headroom for your workflows so that the scheduler does not assign too many runner pods on the same node where the workflow will be executed.

**Comment by turbotankist** [comment]
No, it isn't
4. Hook cant' create a workflow pod. The nodes has no enough cpu or memory to schedule the workflow pod. It must go Pending state, but failed and Terminated by the controller.
expected behavior - a workflow pod goes Pending state - a karpenter run a new eks node. The workflow pod runs on it.

**Comment by nikola-jokic** [comment]
What version of the hook are you using? And are you configuring the hook to use the scheduler, or are you just using the default spec for the container mode kubernetes?

**Comment by nikola-jokic** [comment]
Closing this issue since it is not related to ARC. To add to the explanation, the controller cannot terminate the pod, only kubelet does that when it is out of memory. I don't think this is even a container hook bug. It is more related to the way the cluster is configured, so your pods are terminated with "out of resources" once we try to create a workflow pod.

Please try configuring the hook so it uses kube scheduler, which eliminates the need for the pod to land on the same node where the runner is. If it is not the case, please raise an issue [here](https://github.com/actions/runner-container-hooks)
