### ISSUE TITLE
Open Runner scale set runner dind image to config

### ISSUE THREAD

**Issue by zongsizhang** [actions/actions-runner-controller#3547]
### What would you like added?

As of `v0.9.2`, the helm chart `charts/gha-runner-scale-set` still hardcodes the DinD container specifications.
It will be helpful if we can open the `dind` container to be configurable.

### Why is this needed?

My company needs to run some CI/CD tasks on GPU machines. We need to use the image below instead of the default `dind` image.

I'd be very happy to contribute if you find this case make sense

https://github.com/Extrality/nvidia-dind

**Comment by nikola-jokic** [comment]
Hey @zongsizhang,

We are aware of this need to customize container modes through values.yaml, but currently, we decided on documenting how to apply modifications [here](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#customizing-container-modes).

This issue is related to gha-runner-scale-set, and therefore, should be submitted to the [GitHub Community Support Forum](https://github.com/orgs/community/discussions/categories/actions).
